49  recieved from forex screener
2020-09-08 01:00:21.470097  script ran
49  recieved from forex screener
2020-09-08 01:05:22.922731  script ran
49  recieved from forex screener
2020-09-08 01:10:22.438782  script ran
49  recieved from forex screener
2020-09-08 01:15:23.545224  script ran
49  recieved from forex screener
2020-09-08 01:20:22.748747  script ran
49  recieved from forex screener
2020-09-08 01:25:23.152081  script ran
49  recieved from forex screener
2020-09-08 01:30:27.086413  script ran
49  recieved from forex screener
2020-09-08 01:35:22.826226  script ran
49  recieved from forex screener
2020-09-08 01:40:22.772193  script ran
49  recieved from forex screener
2020-09-08 01:45:24.276870  script ran
49  recieved from forex screener
2020-09-08 01:50:25.106506  script ran
49  recieved from forex screener
2020-09-08 01:55:24.143111  script ran
49  recieved from forex screener
2020-09-08 02:00:23.510284  script ran
49  recieved from forex screener
2020-09-08 02:05:23.752909  script ran
49  recieved from forex screener
2020-09-08 02:10:25.077687  script ran
49  recieved from forex screener
2020-09-08 02:15:23.845796  script ran
49  recieved from forex screener
2020-09-08 02:20:27.601561  script ran
49  recieved from forex screener
2020-09-08 02:25:25.950277  script ran
49  recieved from forex screener
2020-09-08 02:30:22.386229  script ran
49  recieved from forex screener
2020-09-08 02:35:24.324437  script ran
49  recieved from forex screener
2020-09-08 02:40:24.317496  script ran
49  recieved from forex screener
2020-09-08 02:45:23.446685  script ran
49  recieved from forex screener
2020-09-08 02:50:24.083824  script ran
49  recieved from forex screener
2020-09-08 02:55:24.725004  script ran
49  recieved from forex screener
2020-09-08 03:00:24.979694  script ran
49  recieved from forex screener
2020-09-08 03:05:23.471620  script ran
49  recieved from forex screener
2020-09-08 03:10:23.072688  script ran
49  recieved from forex screener
2020-09-08 03:15:24.497146  script ran
49  recieved from forex screener
2020-09-08 03:20:23.664785  script ran
49  recieved from forex screener
2020-09-08 03:25:24.316341  script ran
49  recieved from forex screener
2020-09-08 03:30:23.190074  script ran
49  recieved from forex screener
2020-09-08 03:35:22.550242  script ran
49  recieved from forex screener
2020-09-08 03:40:22.381160  script ran
49  recieved from forex screener
2020-09-08 03:45:23.308126  script ran
49  recieved from forex screener
2020-09-08 03:50:25.549286  script ran
49  recieved from forex screener
2020-09-08 03:55:24.551769  script ran
49  recieved from forex screener
2020-09-08 04:00:24.354076  script ran
49  recieved from forex screener
2020-09-08 04:05:23.034371  script ran
49  recieved from forex screener
2020-09-08 04:10:23.688670  script ran
49  recieved from forex screener
2020-09-08 04:15:24.695856  script ran
49  recieved from forex screener
2020-09-08 04:20:25.351008  script ran
49  recieved from forex screener
2020-09-08 04:25:25.771650  script ran
49  recieved from forex screener
2020-09-08 04:30:25.348162  script ran
49  recieved from forex screener
2020-09-08 04:35:24.060435  script ran
49  recieved from forex screener
2020-09-08 04:40:21.934825  script ran
49  recieved from forex screener
2020-09-08 04:45:24.066771  script ran
49  recieved from forex screener
2020-09-08 04:50:25.030694  script ran
49  recieved from forex screener
2020-09-08 04:55:25.968047  script ran
49  recieved from forex screener
2020-09-08 05:00:23.455148  script ran
49  recieved from forex screener
2020-09-08 05:05:24.479699  script ran
49  recieved from forex screener
2020-09-08 05:10:23.642723  script ran
49  recieved from forex screener
2020-09-08 05:15:23.648772  script ran
49  recieved from forex screener
2020-09-08 05:20:24.585201  script ran
49  recieved from forex screener
2020-09-08 05:25:24.904655  script ran
49  recieved from forex screener
2020-09-08 05:30:27.526976  script ran
49  recieved from forex screener
2020-09-08 05:35:24.141511  script ran
49  recieved from forex screener
2020-09-08 05:40:24.184460  script ran
49  recieved from forex screener
2020-09-08 05:45:23.952429  script ran
49  recieved from forex screener
2020-09-08 05:50:24.176819  script ran
49  recieved from forex screener
2020-09-08 05:55:26.775258  script ran
49  recieved from forex screener
2020-09-08 06:00:27.067849  script ran
49  recieved from forex screener
2020-09-08 06:05:23.106756  script ran
49  recieved from forex screener
2020-09-08 06:10:26.125615  script ran
49  recieved from forex screener
2020-09-08 06:15:24.158826  script ran
49  recieved from forex screener
2020-09-08 06:20:25.949167  script ran
49  recieved from forex screener
2020-09-08 06:25:31.271499  script ran
49  recieved from forex screener
2020-09-08 06:30:31.606160  script ran
49  recieved from forex screener
2020-09-08 06:35:26.644853  script ran
49  recieved from forex screener
2020-09-08 06:40:26.615570  script ran
49  recieved from forex screener
2020-09-08 06:45:26.481082  script ran
49  recieved from forex screener
2020-09-08 06:50:22.375207  script ran
49  recieved from forex screener
2020-09-08 06:55:26.058713  script ran
49  recieved from forex screener
2020-09-08 07:00:25.809886  script ran
49  recieved from forex screener
2020-09-08 07:05:26.251316  script ran
49  recieved from forex screener
2020-09-08 07:10:24.877386  script ran
49  recieved from forex screener
2020-09-08 07:15:25.661080  script ran
49  recieved from forex screener
2020-09-08 07:20:25.325106  script ran
49  recieved from forex screener
2020-09-08 07:25:24.353814  script ran
49  recieved from forex screener
2020-09-08 07:30:26.337638  script ran
49  recieved from forex screener
2020-09-08 07:35:24.875756  script ran
49  recieved from forex screener
2020-09-08 07:40:26.582903  script ran
49  recieved from forex screener
2020-09-08 07:45:25.227552  script ran
49  recieved from forex screener
2020-09-08 07:50:25.884928  script ran
49  recieved from forex screener
2020-09-08 07:55:22.370531  script ran
0  recieved from forex screener
49  recieved from forex screener
2020-09-08 08:00:30.582672  script ran
49  recieved from forex screener
2020-09-08 08:05:26.525233  script ran
49  recieved from forex screener
2020-09-08 08:10:23.716949  script ran
49  recieved from forex screener
2020-09-08 08:15:24.984422  script ran
49  recieved from forex screener
2020-09-08 08:20:25.575424  script ran
49  recieved from forex screener
2020-09-08 08:25:24.243440  script ran
49  recieved from forex screener
2020-09-08 08:30:24.549286  script ran
49  recieved from forex screener
2020-09-08 08:35:27.375737  script ran
49  recieved from forex screener
2020-09-08 08:40:24.132769  script ran
49  recieved from forex screener
2020-09-08 08:45:27.243668  script ran
49  recieved from forex screener
2020-09-08 08:50:29.118414  script ran
49  recieved from forex screener
2020-09-08 08:55:27.364177  script ran
49  recieved from forex screener
2020-09-08 09:00:26.597222  script ran
49  recieved from forex screener
2020-09-08 09:05:26.459796  script ran
49  recieved from forex screener
2020-09-08 09:10:28.899657  script ran
49  recieved from forex screener
2020-09-08 09:15:28.671169  script ran
49  recieved from forex screener
2020-09-08 09:20:27.307660  script ran
49  recieved from forex screener
2020-09-08 09:25:27.538282  script ran
49  recieved from forex screener
2020-09-08 09:30:26.270240  script ran
49  recieved from forex screener
2020-09-08 09:35:28.644694  script ran
49  recieved from forex screener
2020-09-08 09:40:25.820094  script ran
49  recieved from forex screener
2020-09-08 09:45:28.055294  script ran
49  recieved from forex screener
2020-09-08 09:50:27.393941  script ran
49  recieved from forex screener
2020-09-08 09:55:26.319779  script ran
49  recieved from forex screener
2020-09-08 10:00:25.722301  script ran
49  recieved from forex screener
2020-09-08 10:05:25.718430  script ran
49  recieved from forex screener
2020-09-08 10:10:27.834675  script ran
49  recieved from forex screener
2020-09-08 10:15:25.325533  script ran
49  recieved from forex screener
2020-09-08 10:20:28.606865  script ran
49  recieved from forex screener
2020-09-08 10:25:28.650286  script ran
49  recieved from forex screener
2020-09-08 10:30:27.151639  script ran
49  recieved from forex screener
2020-09-08 10:35:25.116606  script ran
49  recieved from forex screener
2020-09-08 10:40:26.922487  script ran
49  recieved from forex screener
2020-09-08 10:45:25.704260  script ran
49  recieved from forex screener
2020-09-08 10:50:25.600808  script ran
49  recieved from forex screener
2020-09-08 10:55:26.823888  script ran
49  recieved from forex screener
2020-09-08 11:00:26.693753  script ran
49  recieved from forex screener
2020-09-08 11:05:26.175749  script ran
49  recieved from forex screener
2020-09-08 11:10:24.065180  script ran
49  recieved from forex screener
2020-09-08 11:15:24.416129  script ran
49  recieved from forex screener
2020-09-08 11:20:26.078291  script ran
49  recieved from forex screener
2020-09-08 11:25:26.093295  script ran
49  recieved from forex screener
2020-09-08 11:30:25.768752  script ran
49  recieved from forex screener
2020-09-08 11:35:25.642006  script ran
49  recieved from forex screener
2020-09-08 11:40:26.057909  script ran
49  recieved from forex screener
2020-09-08 11:45:26.360227  script ran
49  recieved from forex screener
2020-09-08 11:50:25.614514  script ran
49  recieved from forex screener
2020-09-08 11:55:27.593835  script ran
49  recieved from forex screener
2020-09-08 12:00:27.482691  script ran
49  recieved from forex screener
2020-09-08 12:05:25.291058  script ran
49  recieved from forex screener
2020-09-08 12:10:25.031533  script ran
49  recieved from forex screener
2020-09-08 12:15:24.772132  script ran
49  recieved from forex screener
2020-09-08 12:20:23.254897  script ran
49  recieved from forex screener
2020-09-08 12:25:24.985394  script ran
49  recieved from forex screener
2020-09-08 12:30:26.623052  script ran
49  recieved from forex screener
2020-09-08 12:35:24.482355  script ran
49  recieved from forex screener
2020-09-08 12:40:23.618104  script ran
49  recieved from forex screener
2020-09-08 12:45:23.477784  script ran
49  recieved from forex screener
2020-09-08 12:50:24.584132  script ran
49  recieved from forex screener
2020-09-08 12:55:26.176986  script ran
49  recieved from forex screener
2020-09-08 13:00:53.280448  script ran
49  recieved from forex screener
2020-09-08 13:05:29.099237  script ran
49  recieved from forex screener
2020-09-08 13:10:28.233537  script ran
49  recieved from forex screener
2020-09-08 13:15:25.643768  script ran
49  recieved from forex screener
2020-09-08 13:20:26.064707  script ran
49  recieved from forex screener
2020-09-08 13:25:26.891576  script ran
49  recieved from forex screener
2020-09-08 13:30:26.930814  script ran
49  recieved from forex screener
2020-09-08 13:35:27.867215  script ran
49  recieved from forex screener
2020-09-08 13:40:27.147005  script ran
Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 255, in main
    create_html(prem, vip)
  File "/home/ubuntu/trends-script/scraper.py", line 179, in create_html
    platinum_result = get_platinum_screener_list()
  File "/home/ubuntu/trends-script/forex_screener_scrap.py", line 19, in get_platinum_screener_list
    data = driver.find_element_by_xpath('//*[@id="js-screener-container"]/div[4]/table/tbody').text
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="js-screener-container"]/div[4]/table/tbody"}
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.231
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.602
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.759
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.215
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.543
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.175
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.399
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.770
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.464
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.749
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.093
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.813
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.733
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.201
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.613
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.438
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 27, in get_html_from_site
    driver = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 36, in get_html_from_site
    liquidity_providers.click()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="a-b-c L-M-j L-M-j-r-t" title="" role="button" aria-pressed="false" id=":1" style="user-select: none;">...</div> is not clickable at point (280, 442). Other element would receive the click: <div class="L-M-Qb-tb L-M-Qb-Tb-Sb">...</div>
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.238
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.542
  (Session info: headless chrome=83.0.4103.97)

Traceback (most recent call last):
  File "/home/ubuntu/trends-script/scraper.py", line 259, in <module>
    main()
  File "/home/ubuntu/trends-script/scraper.py", line 252, in main
    htmlstring = get_html_from_site()
  File "/home/ubuntu/trends-script/scraper.py", line 30, in get_html_from_site
    driver.get(start_url)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.156
  (Session info: headless chrome=83.0.4103.97)

49  recieved from forex screener
2020-09-08 15:56:35.157741  script ran
49  recieved from forex screener
2020-09-08 16:00:32.732697  script ran
49  recieved from forex screener
2020-09-08 16:05:31.813444  script ran
49  recieved from forex screener
2020-09-08 16:10:29.255226  script ran
49  recieved from forex screener
2020-09-08 16:15:26.867461  script ran
49  recieved from forex screener
2020-09-08 16:20:28.929446  script ran
49  recieved from forex screener
2020-09-08 16:25:27.808965  script ran
49  recieved from forex screener
2020-09-08 16:30:28.737178  script ran
49  recieved from forex screener
2020-09-08 16:35:26.008825  script ran
49  recieved from forex screener
2020-09-08 16:40:27.225464  script ran
49  recieved from forex screener
2020-09-08 16:45:26.677204  script ran
49  recieved from forex screener
2020-09-08 16:50:27.873887  script ran
49  recieved from forex screener
2020-09-08 16:55:26.280639  script ran
49  recieved from forex screener
2020-09-08 17:00:29.416800  script ran
49  recieved from forex screener
2020-09-08 17:05:30.803761  script ran
49  recieved from forex screener
2020-09-08 17:10:26.971619  script ran
49  recieved from forex screener
2020-09-08 17:15:28.404400  script ran
49  recieved from forex screener
2020-09-08 17:20:30.929361  script ran
49  recieved from forex screener
2020-09-08 17:25:25.125261  script ran
49  recieved from forex screener
2020-09-08 17:30:26.203216  script ran
49  recieved from forex screener
2020-09-08 17:35:29.145122  script ran
49  recieved from forex screener
2020-09-08 17:40:27.352655  script ran
